kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack-notifications
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 10m
      routes:
        - receiver: slack-notifications
        # Send severity=slack alerts to slack.
          match:
            severity: slack
          group_wait: 10s
          repeat_interval: 1m
      
    receivers:
    - name: slack-notifications
      slack_configs:
      - channel: "#<ChannelName>"
        send_resolved: true
        api_url: "<WebHook_Slack>"
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
