name: Build
on:
  push:
    branches:
      - main
jobs:
  build-and-debloy:
    name: Build
    runs-on: "self-hosted"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: sonarsource/sonarqube-scan-action@master   
        env:
            SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
            SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  
      - name: Disable treating warnings as errors
        run: echo "CI=false" >> $GITHUB_ENV         
      - name: Get application version
        id: get-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Use Node.js
        uses: actions/setup-node@v3 
      - run: npm ci --legacy-peer-deps
      - run: npm run build --if-present 
      - name: Build artifact
        run:  npm pack 

      - name: Login to Nexus
        run: npm login --registry=${{ secrets.NEXUS_REPO }} --always-auth
        env:
         NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
         NEXUS_EMAIL: ${{ secrets.NEXUS_EMAIL }} 
      - name: Publish NPM package to Nexus
        run: npm publish ./horizon-${{ steps.get-version.outputs.version }}.tgz --registry=${{ secrets.NEXUS_REPO }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/horizonweb:${{ steps.get-version.outputs.version }} .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/horizonweb:${{ steps.get-version.outputs.version }}
      - name: Create Namespace if not exists
        id: create-namespace
        run: |
          kubectl config use-context ${{ secrets.LOCAL_CONTEXT }}

          namespace="webapp"
          if ! kubectl get namespace "${namespace}" --output=name 2>/dev/null; then
            echo "Namespace does not exist. Creating..."
            kubectl create namespace "${namespace}"
            echo "::set-output name=namespace::${namespace}"
          else
            echo "Namespace already exists."
            echo "::set-output name=namespace::${namespace}"
          fi

      - name: Deploy to Local Cluster 
        env:
            NAMESPACE: ${{ steps.create-namespace.outputs.namespace }}
            IMAGE_REFERENCE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/horizonweb:${{ steps.get-version.outputs.version }}
        run: |
         aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com
         kubectl config use-context ${{ secrets.LOCAL_CONTEXT }}
         secret="my-registry-key"
         if ! kubectl get secret "${secret}" -n $NAMESPACE   2>/dev/null; then
          echo "Secret does not exist. Creating..."
          kubectl create secret generic "${secret}" --from-file=.dockerconfigjson=/home/runner/.docker/config.json --type=kubernetes.io/dockerconfigjson -n $NAMESPACE
         elif kubectl get secret "${secret}" -n $NAMESPACE   2>/dev/null; then
          echo "Secret already exists."
          kubectl delete secret  "${secret}"  -n $NAMESPACE
          kubectl create secret generic "${secret}" --from-file=.dockerconfigjson=/home/runner/.docker/config.json --type=kubernetes.io/dockerconfigjson -n $NAMESPACE
         fi

          kubectl apply -f ./kubernetes/Local_test/ServiceAccount.yaml -n  $NAMESPACE
          kubectl apply -f ./kubernetes/Local_test/Volume.yaml -n  $NAMESPACE
          cat ./kubernetes/Local_test/Deloyement.yaml | envsubst | kubectl apply -n   $NAMESPACE  -f -
          kubectl apply -f ./kubernetes/Local_test/service.yaml -n  $NAMESPACE