- hosts: MASTERS
  become: yes
  become_user: root
  tasks:
   - name: Disabele ufw
     shell: sudo ufw disable
   - name: Intilizing Kubernetes Cluster
     command: kubeadm init --apiserver-advertise-address="{{ansible_host}}" --pod-network-cidr 192.168.0.0/16
   - pause: seconds=30
   - name: Create .kube directory
     become: true
     file:
        path: "/home/{{ansible_user}}/.kube"
        state: directory
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        mode: '0700'
   - name: Copy admin.conf to user's kubeconfig
     become: true
     copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ansible_user}}/.kube/config"
        remote_src: yes
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
        mode: '0600'
        force: yes
        backup: yes
        validate: kubectl --kubeconfig=%s config view
   - name: Add KUBECONFIG export to root user's shell profile
     lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
        state: present


